import type { PosterDef } from "./PosterComp";

/* Poster/social graphic definitions. Formats: 45 = IG feed 1080x1350,
   story = 1080x1920, sq = 1080x1080, print = A3 ratio (render --scale 2.83
   for 300dpi). Stills come from one-current-app/scripts/promo-stills.mjs. */

const F = {
  "45": { w: 1080, h: 1350 },
  story: { w: 1080, h: 1920 },
  sq: { w: 1080, h: 1080 },
  print: { w: 1240, h: 1754 },
} as const;

type Concept = Omit<PosterDef, "id" | "w" | "h"> & { key: string; formats: (keyof typeof F)[] };

const concepts: Concept[] = [
  {
    key: "p01-hero",
    formats: ["45", "story", "sq", "print"],
    mood: "river",
    layout: "device",
    still: "still-hero.png",
    headline: "Your mind is one current.",
    sub: "A quiet map of everything pulling at you.",
  },
  {
    key: "p02-louder",
    formats: ["45", "story"],
    mood: "night",
    layout: "device",
    still: "still-loud.png",
    headline: "Ignored threads get louder.",
    sub: "Every undecided day adds a little weight.",
  },
  {
    key: "p03-integrate",
    formats: ["45", "story"],
    mood: "river",
    layout: "device",
    still: "still-reclaim.png",
    headline: "Get yourself back.",
    sub: "Resolved threads fold back into your line — and what they held comes home.",
  },
  {
    key: "p04-themes",
    formats: ["45", "story"],
    mood: "dusk",
    layout: "grid",
    stills: [
      "still-theme-demonfire.png",
      "still-theme-koipond.png",
      "still-theme-carnival.png",
      "still-theme-catnap.png",
      "still-theme-abyss.png",
      "still-theme-gravemist.png",
    ],
    kicker: "One Current Pro",
    headline: "Every open thread becomes a creature.",
  },
  {
    key: "p05-pip",
    formats: ["45", "story"],
    mood: "warm",
    layout: "device",
    still: "still-pip.png",
    kicker: "Meet Pip",
    headline: "A companion on your timeline.",
    sub: "He keeps watch over your threads.",
  },
  {
    key: "p06-privacy",
    formats: ["45", "story", "sq"],
    mood: "river",
    layout: "quote",
    kicker: "One Current",
    headline: "Nothing is sent anywhere.",
    sub: "Your threads live on your device. No feed. No tracking. Just your current.",
  },
  {
    key: "p07-split",
    formats: ["sq", "story"],
    mood: "river",
    layout: "quote",
    headline: "“That is the split — not you.”",
    sub: "One Current shows how much of you moves with your main line — and the one decision that would gather you most.",
  },
  {
    key: "p08-action",
    formats: ["sq", "story"],
    mood: "warm",
    layout: "quote",
    headline: "“An action counts. So does deciding that nothing can be done.”",
    sub: "Every thread needs a decision, not a solution.",
  },
  {
    key: "p09-practice",
    formats: ["45", "story"],
    mood: "river",
    layout: "split",
    deviceKind: "browser",
    still: "still-practice.png",
    kicker: "For therapists",
    headline: "The real picture, on one timeline.",
    bullets: [
      "A shared window, drawn like the client lived it",
      "Only what the client chose to share",
      "Session notes stay on your device",
    ],
  },
  {
    key: "p10-pro",
    formats: ["45", "story"],
    mood: "dusk",
    layout: "split",
    deviceKind: "phone",
    still: "still-share.png",
    kicker: "One Current Pro",
    headline: "Carry as many threads as your days do.",
    badge: "€6/month",
    bullets: [
      "Unlimited open threads",
      "Share with your psychologist",
      "Seven living creature themes",
    ],
  },
  // ---- campaign: worry hooks — one universal thread title per poster ----
  ...[
    ["w1-message", "The unanswered message.", "river"],
    ["w2-rent", "The rent increase letter.", "warm"],
    ["w3-further", "Everyone seems further along than me.", "night"],
    ["w4-sleep", "My sleep is a mess again.", "dusk"],
    ["w5-argument", "The argument I keep replaying.", "river"],
    ["w6-waiting", "Waiting for news that isn't coming fast enough.", "warm"],
  ].map(([key, headline, mood]) => ({
    key: key as string,
    formats: ["45", "story"] as (keyof typeof F)[],
    mood: mood as Concept["mood"],
    layout: "quote" as const,
    kicker: "One Current",
    headline: headline as string,
    sub: "Whatever pulls at you — name it, see it on your line, decide something small.",
  })),
  // ---- campaign: one poster per creature theme ----
  ...[
    ["c1-demonfire", "demonfire", "Face it kindly, and it settles.", "night"],
    ["c2-koipond", "koipond", "Feed it a decision — the pond stills.", "river"],
    ["c3-carnival", "carnival", "The longer it waits, the tighter it swells.", "warm"],
    ["c4-catnap", "catnap", "Answer it, and it curls up.", "river"],
    ["c5-abyss", "abyss", "The louder it grows, the brighter its lure.", "night"],
    ["c6-pompom", "pompom", "Leave it waiting, and it barks.", "warm"],
    ["c7-gravemist", "gravemist", "Its wail widens until you answer.", "dusk"],
  ].map(([key, theme, headline, mood]) => ({
    key: key as string,
    formats: ["45", "story"] as (keyof typeof F)[],
    mood: mood as Concept["mood"],
    layout: "device" as const,
    still: `still-theme-${theme}.png`,
    kicker: "One Current Pro",
    headline: headline as string,
  })),
  {
    key: "f1-wholeness",
    formats: ["45", "story"],
    mood: "river",
    layout: "device",
    still: "still-wholeness.png",
    headline: "How much of you is here today?",
    sub: "The wholeness gauge answers honestly — and points at the one decision that gathers you most.",
  },
  // ---- campaign wave 3: Pip says, wholeness words, manifesto, feature minis ----
  ...[
    ["q1-pip-hi", "“Hi! I'm Pip! I live on your timelines.”", "Your companion in One Current — he watches your threads with you.", "warm"],
    ["q2-pip-named", "“Named things are easier to work with.”", "When something new lands on your mind, give it a name.", "river"],
    ["q3-pip-merge", "“Merge it back — the energy comes home.”", "Resolved threads rejoin your main line.", "warm"],
    ["q4-pip-got-this", "“You've got this.”", "Pip keeps watch over your threads, every day.", "river"],
  ].map(([key, headline, sub, mood]) => ({
    key: key as string,
    formats: ["45", "story"] as (keyof typeof F)[],
    mood: mood as Concept["mood"],
    layout: "quote" as const,
    kicker: "Pip says",
    headline: headline as string,
    sub: sub as string,
  })),
  ...[
    ["v1-whole", "whole.", "Nothing is pulling you apart. Expect a steady, present day — protect it.", "river"],
    ["v2-gathered", "gathered.", "A few threads are open, but you are mostly moving as one.", "warm"],
    ["v3-pulled-apart", "pulled apart.", "Several threads are pulling at once. One decision starts bringing you back.", "dusk"],
    ["v4-scattered", "scattered.", "Today can feel like living several days at once. That is the split — not you.", "night"],
  ].map(([key, headline, sub, mood]) => ({
    key: key as string,
    formats: ["45", "story"] as (keyof typeof F)[],
    mood: mood as Concept["mood"],
    layout: "quote" as const,
    kicker: "How much of you is here today?",
    headline: headline as string,
    sub: sub as string,
  })),
  ...[
    ["m1-mainline", "Your life continues on one main line.", "Everything else is a thread that can come back.", "river"],
    ["m2-not-noise", "Not noise inside your head. A thread beside your line.", "See what pulls at you — and what it needs.", "dusk"],
    ["m3-come-home", "Every thread can come home.", "Decided, integrated, or set down kindly.", "warm"],
  ].map(([key, headline, sub, mood]) => ({
    key: key as string,
    formats: ["45", "story"] as (keyof typeof F)[],
    mood: mood as Concept["mood"],
    layout: "quote" as const,
    kicker: "One Current",
    headline: headline as string,
    sub: sub as string,
  })),
  {
    key: "f2-history",
    formats: ["45", "story"],
    mood: "warm",
    layout: "device",
    still: "still-history.png",
    headline: "Days that read like a story.",
    sub: "Every decision, quietly recorded — energy, steps, and what came home.",
  },
  {
    key: "f3-actions",
    formats: ["45", "story"],
    mood: "river",
    layout: "device",
    still: "still-actions.png",
    headline: "Small honest steps, all in one place.",
    sub: "What each thread needs from you today.",
  },
  {
    key: "f4-practice-quote",
    formats: ["45", "story"],
    mood: "river",
    layout: "quote",
    kicker: "One Current — Practice",
    headline: "Only what the client chose to share.",
    sub: "A shared window on a timeline — session notes never leave your device.",
  },
];

export const posters: PosterDef[] = concepts.flatMap((c) =>
  c.formats.map((f) => {
    const { key, formats, ...rest } = c;
    return { id: `${key}-${f}`, ...F[f], ...rest };
  }),
);
