import type { PosterDef } from "./PosterComp";

/* Poster/social graphic definitions. Formats: 45 = IG feed 1080x1350,
   story = 1080x1920, sq = 1080x1080, print = A3 ratio (render --scale 2.83
   for 300dpi). Stills come from one-current-app/scripts/promo-stills.mjs. */

const F = {
  "45": { w: 1080, h: 1350 },
  story: { w: 1080, h: 1920 },
  sq: { w: 1080, h: 1080 },
  print: { w: 1240, h: 1754 },
} as const;

type Concept = Omit<PosterDef, "id" | "w" | "h"> & { key: string; formats: (keyof typeof F)[] };

const concepts: Concept[] = [
  {
    key: "p01-hero",
    formats: ["45", "story", "sq", "print"],
    mood: "river",
    layout: "device",
    still: "still-hero.png",
    headline: "Your mind is one current.",
    sub: "A quiet map of everything pulling at you.",
  },
  {
    key: "p02-louder",
    formats: ["45", "story"],
    mood: "night",
    layout: "device",
    still: "still-loud.png",
    headline: "Ignored threads get louder.",
    sub: "Every undecided day adds a little weight.",
  },
  {
    key: "p03-integrate",
    formats: ["45", "story"],
    mood: "river",
    layout: "device",
    still: "still-reclaim.png",
    headline: "Get yourself back.",
    sub: "Resolved threads fold back into your line — and what they held comes home.",
  },
  {
    key: "p04-themes",
    formats: ["45", "story"],
    mood: "dusk",
    layout: "grid",
    stills: [
      "still-theme-demonfire.png",
      "still-theme-koipond.png",
      "still-theme-carnival.png",
      "still-theme-catnap.png",
      "still-theme-abyss.png",
      "still-theme-gravemist.png",
    ],
    kicker: "One Current Pro",
    headline: "Every open thread becomes a creature.",
  },
  {
    key: "p05-pip",
    formats: ["45", "story"],
    mood: "warm",
    layout: "device",
    still: "still-pip.png",
    kicker: "Meet Pip",
    headline: "A companion on your timeline.",
    sub: "He keeps watch over your threads.",
  },
  {
    key: "p06-privacy",
    formats: ["45", "story", "sq"],
    mood: "river",
    layout: "quote",
    kicker: "One Current",
    headline: "Nothing is sent anywhere.",
    sub: "Your threads live on your device. No feed. No tracking. Just your current.",
  },
  {
    key: "p07-split",
    formats: ["sq", "story"],
    mood: "river",
    layout: "quote",
    headline: "“That is the split — not you.”",
    sub: "One Current shows how much of you moves with your main line — and the one decision that would gather you most.",
  },
  {
    key: "p08-action",
    formats: ["sq", "story"],
    mood: "warm",
    layout: "quote",
    headline: "“An action counts. So does deciding that nothing can be done.”",
    sub: "Every thread needs a decision, not a solution.",
  },
  {
    key: "p09-practice",
    formats: ["45", "story"],
    mood: "river",
    layout: "split",
    deviceKind: "browser",
    still: "still-practice.png",
    kicker: "For therapists",
    headline: "The real picture, on one timeline.",
    bullets: [
      "A shared window, drawn like the client lived it",
      "Only what the client chose to share",
      "Session notes stay on your device",
    ],
  },
  {
    key: "p10-pro",
    formats: ["45", "story"],
    mood: "dusk",
    layout: "split",
    deviceKind: "phone",
    still: "still-share.png",
    kicker: "One Current Pro",
    headline: "Carry as many threads as your days do.",
    badge: "€6/month",
    bullets: [
      "Unlimited open threads",
      "Share with your psychologist",
      "Seven living creature themes",
    ],
  },
  // ---- campaign: worry hooks — one universal thread title per poster ----
  ...[
    ["w1-message", "The unanswered message.", "river"],
    ["w2-rent", "The rent increase letter.", "warm"],
    ["w3-further", "Everyone seems further along than me.", "night"],
    ["w4-sleep", "My sleep is a mess again.", "dusk"],
    ["w5-argument", "The argument I keep replaying.", "river"],
    ["w6-waiting", "Waiting for news that isn't coming fast enough.", "warm"],
  ].map(([key, headline, mood]) => ({
    key: key as string,
    formats: ["45", "story"] as (keyof typeof F)[],
    mood: mood as Concept["mood"],
    layout: "quote" as const,
    kicker: "One Current",
    headline: headline as string,
    sub: "Whatever pulls at you — name it, see it on your line, decide something small.",
  })),
  // ---- campaign: one poster per creature theme ----
  ...[
    ["c1-demonfire", "demonfire", "Face it kindly, and it settles.", "night"],
    ["c2-koipond", "koipond", "Feed it a decision — the pond stills.", "river"],
    ["c3-carnival", "carnival", "The longer it waits, the tighter it swells.", "warm"],
    ["c4-catnap", "catnap", "Answer it, and it curls up.", "river"],
    ["c5-abyss", "abyss", "The louder it grows, the brighter its lure.", "night"],
    ["c6-pompom", "pompom", "Leave it waiting, and it barks.", "warm"],
    ["c7-gravemist", "gravemist", "Its wail widens until you answer.", "dusk"],
  ].map(([key, theme, headline, mood]) => ({
    key: key as string,
    formats: ["45", "story"] as (keyof typeof F)[],
    mood: mood as Concept["mood"],
    layout: "device" as const,
    still: `still-theme-${theme}.png`,
    kicker: "One Current Pro",
    headline: headline as string,
  })),
  {
    key: "f1-wholeness",
    formats: ["45", "story"],
    mood: "river",
    layout: "device",
    still: "still-wholeness.png",
    headline: "How much of you is here today?",
    sub: "The wholeness gauge answers honestly — and points at the one decision that gathers you most.",
  },
  // ---- campaign wave 3: Pip says, wholeness words, manifesto, feature minis ----
  ...[
    ["q1-pip-hi", "“Hi! I'm Pip! I live on your timelines.”", "Your companion in One Current — he watches your threads with you.", "warm"],
    ["q2-pip-named", "“Named things are easier to work with.”", "When something new lands on your mind, give it a name.", "river"],
    ["q3-pip-merge", "“Merge it back — the energy comes home.”", "Resolved threads rejoin your main line.", "warm"],
    ["q4-pip-got-this", "“You've got this.”", "Pip keeps watch over your threads, every day.", "river"],
  ].map(([key, headline, sub, mood]) => ({
    key: key as string,
    formats: ["45", "story"] as (keyof typeof F)[],
    mood: mood as Concept["mood"],
    layout: "quote" as const,
    kicker: "Pip says",
    headline: headline as string,
    sub: sub as string,
  })),
  ...[
    ["v1-whole", "whole.", "Nothing is pulling you apart. Expect a steady, present day — protect it.", "river"],
    ["v2-gathered", "gathered.", "A few threads are open, but you are mostly moving as one.", "warm"],
    ["v3-pulled-apart", "pulled apart.", "Several threads are pulling at once. One decision starts bringing you back.", "dusk"],
    ["v4-scattered", "scattered.", "Today can feel like living several days at once. That is the split — not you.", "night"],
  ].map(([key, headline, sub, mood]) => ({
    key: key as string,
    formats: ["45", "story"] as (keyof typeof F)[],
    mood: mood as Concept["mood"],
    layout: "quote" as const,
    kicker: "How much of you is here today?",
    headline: headline as string,
    sub: sub as string,
  })),
  ...[
    ["m1-mainline", "Your life continues on one main line.", "Everything else is a thread that can come back.", "river"],
    ["m2-not-noise", "Not noise inside your head. A thread beside your line.", "See what pulls at you — and what it needs.", "dusk"],
    ["m3-come-home", "Every thread can come home.", "Decided, integrated, or set down kindly.", "warm"],
  ].map(([key, headline, sub, mood]) => ({
    key: key as string,
    formats: ["45", "story"] as (keyof typeof F)[],
    mood: mood as Concept["mood"],
    layout: "quote" as const,
    kicker: "One Current",
    headline: headline as string,
    sub: sub as string,
  })),
  {
    key: "f2-history",
    formats: ["45", "story"],
    mood: "warm",
    layout: "device",
    still: "still-history.png",
    headline: "Days that read like a story.",
    sub: "Every decision, quietly recorded — energy, steps, and what came home.",
  },
  {
    key: "f3-actions",
    formats: ["45", "story"],
    mood: "river",
    layout: "device",
    still: "still-actions.png",
    headline: "Small honest steps, all in one place.",
    sub: "What each thread needs from you today.",
  },
  {
    key: "f4-practice-quote",
    formats: ["45", "story"],
    mood: "river",
    layout: "quote",
    kicker: "One Current — Practice",
    headline: "Only what the client chose to share.",
    sub: "A shared window on a timeline — session notes never leave your device.",
  },
  // ---- campaign wave 4: positioning, rituals, contrasts, feelings, practice ----
  ...[
    ["a1-no-streaks", "No streaks. No guilt. Just your current.", "Nothing to keep up. Only what is true today.", "river", "One Current"],
    ["a2-not-todo", "Not a to-do list. A map of your attention.", "See what pulls at you — and what it actually needs.", "warm", "One Current"],
    ["a3-opposite-feed", "The opposite of a feed.", "Nothing scrolls here. Your threads wait quietly until you're ready.", "night", "One Current"],
    ["a4-close-lighter", "An app you close feeling lighter.", "Open it, decide something small, return to your life.", "dusk", "One Current"],
    ["r1-morning", "Morning coffee: what's pulling at today?", "One look at your line, one honest answer.", "warm", "A small ritual"],
    ["r2-bed", "Before bed: one honest decision.", "An action counts. So does deciding nothing can be done.", "night", "A small ritual"],
    ["r3-sunday", "Sunday evening: read your week like a story.", "Every decision, quietly recorded in History.", "river", "A small ritual"],
    ["b1-visible", "Same worries. Finally visible.", "A vague weight becomes lines you can answer.", "river", "One Current"],
    ["b2-one-thing", "From everything-at-once to one thing today.", "The gauge points at the decision that gathers you most.", "dusk", "One Current"],
    ["b3-ten-threads", "Ten open threads. One line through them all.", "Your life continues on one main line.", "warm", "One Current"],
    ["e1-feelings", "worry · dread · guilt · overwhelm", "Each one can live on a line — instead of in your chest.", "night", "One Current"],
    ["t1-month", "Your client's month, on one page.", "The shared window, drawn the way their own app drew it.", "river", "One Current — Practice"],
    ["t2-recall", "Less recall. More reality.", "Sessions start from what actually happened in between.", "warm", "One Current — Practice"],
  ].map(([key, headline, sub, mood, kicker]) => ({
    key: key as string,
    formats: ["45", "story"] as (keyof typeof F)[],
    mood: mood as Concept["mood"],
    layout: "quote" as const,
    kicker: kicker as string,
    headline: headline as string,
    sub: sub as string,
  })),
  // ---- campaign wave 5: the app, placed differently ----
  {
    key: "x1-tilt-hero",
    formats: ["45", "story"],
    mood: "river",
    layout: "tilt",
    still: "still-hero.png",
    headline: "All of it, on one line.",
    sub: "Threads you can see are threads you can answer.",
  },
  {
    key: "x2-peek-loud",
    formats: ["45", "story"],
    mood: "dusk",
    layout: "peek",
    still: "still-loud.png",
    headline: "It's all still there. Just quieter.",
    sub: "Loud weeks turn into lines you can work with.",
  },
  {
    key: "x3-duo-live-read",
    formats: ["45", "story"],
    mood: "warm",
    layout: "duo",
    stills: ["still-hero.png", "still-history.png"],
    headline: "Live it. Then read it.",
    sub: "Your current by day, your story by night.",
  },
  {
    key: "x4-fan-themes",
    formats: ["45", "story"],
    mood: "dusk",
    layout: "fan",
    stills: ["still-theme-koipond.png", "still-theme-carnival.png", "still-theme-gravemist.png"],
    kicker: "One Current Pro",
    headline: "Pick the world your threads live in.",
  },
  {
    key: "x5-topbleed-wholeness",
    formats: ["45", "story"],
    mood: "night",
    layout: "top-bleed",
    still: "still-wholeness.png",
    headline: "Check in with yourself — not with a feed.",
    sub: "One honest gauge, one next decision.",
  },
  {
    key: "x6-zoom-dragon",
    formats: ["45", "story"],
    mood: "night",
    layout: "zoom",
    still: "still-theme-demonfire.png",
    focus: { x: 0.48, y: 0.33, zoom: 2.2 },
    kicker: "One Current Pro",
    headline: "Small dragons. Honest answers.",
    sub: "Face a thread kindly, and it settles.",
  },
  {
    key: "x7-duo-decide",
    formats: ["45", "story"],
    mood: "river",
    layout: "duo",
    stills: ["still-reclaim.png", "still-wholeness.png"],
    headline: "Decide. Integrate. Come home.",
    sub: "What a thread held returns to you.",
  },
  {
    key: "x8-tilt-pip",
    formats: ["45", "story"],
    mood: "warm",
    layout: "tilt",
    tiltSide: "left",
    still: "still-pip.png",
    headline: "Never alone on your line.",
    sub: "Pip patrols your threads with you.",
  },
  // ---- campaign wave 6: more creative device compositions ----
  {
    key: "y1-tilt-koi",
    formats: ["45", "story"],
    mood: "river",
    layout: "tilt",
    still: "still-theme-koipond.png",
    kicker: "One Current Pro",
    headline: "Quiet water. Honest threads.",
  },
  {
    key: "y2-tilt-history",
    formats: ["45", "story"],
    mood: "warm",
    layout: "tilt",
    tiltSide: "left",
    still: "still-history.png",
    headline: "A week, written by your decisions.",
  },
  {
    key: "y3-peek-abyss",
    formats: ["45", "story"],
    mood: "night",
    layout: "peek",
    still: "still-theme-abyss.png",
    kicker: "One Current Pro",
    headline: "Even the deep ones surface here.",
    sub: "The louder a thread grows, the brighter its lure.",
  },
  {
    key: "y4-peek-reclaim",
    formats: ["45", "story"],
    mood: "river",
    layout: "peek",
    still: "still-reclaim.png",
    headline: "The moment it comes home.",
    sub: "Integrate a finished thread and its energy returns.",
  },
  {
    key: "y5-duo-soft",
    formats: ["45", "story"],
    mood: "warm",
    layout: "duo",
    stills: ["still-theme-catnap.png", "still-theme-pompom.png"],
    kicker: "One Current Pro",
    headline: "Soft company for loud days.",
  },
  {
    key: "y6-duo-clear",
    formats: ["45", "story"],
    mood: "dusk",
    layout: "duo",
    stills: ["still-loud.png", "still-hero.png"],
    headline: "From loud weeks to one clear line.",
    sub: "Decisions quiet threads. Every time.",
  },
  {
    key: "y7-fan-dark",
    formats: ["45", "story"],
    mood: "night",
    layout: "fan",
    stills: ["still-theme-demonfire.png", "still-theme-abyss.png", "still-theme-gravemist.png"],
    kicker: "One Current Pro",
    headline: "The dark ones live here too.",
  },
  {
    key: "y8-fan-see",
    formats: ["45", "story"],
    mood: "river",
    layout: "fan",
    stills: ["still-wholeness.png", "still-hero.png", "still-history.png"],
    headline: "See it. Weigh it. Remember it.",
  },
  {
    key: "y9-topbleed-actions",
    formats: ["45", "story"],
    mood: "warm",
    layout: "top-bleed",
    still: "still-actions.png",
    headline: "Today's steps, right below.",
    sub: "Small, honest, and already decided.",
  },
  {
    key: "y10-topbleed-carnival",
    formats: ["45", "story"],
    mood: "dusk",
    layout: "top-bleed",
    still: "still-theme-carnival.png",
    kicker: "One Current Pro",
    headline: "Some days are a carnival. Answer anyway.",
  },
  {
    key: "y11-zoom-pip",
    formats: ["45", "story"],
    mood: "warm",
    layout: "zoom",
    still: "still-pip.png",
    focus: { x: 0.605, y: 0.205, zoom: 3.2 },
    headline: "Someone's watching your threads. Kindly.",
    sub: "Pip inspects what you haven't decided on yet.",
  },
  {
    key: "y12-zoom-koi",
    formats: ["45", "story"],
    mood: "river",
    layout: "zoom",
    still: "still-theme-koipond.png",
    focus: { x: 0.48, y: 0.33, zoom: 2.2 },
    kicker: "One Current Pro",
    headline: "Feed it a decision.",
    sub: "The koi settles. The pond stills.",
  },
  // ---- campaign wave 7: zoom-circle details ----
  ...[
    ["z1-zoom-balloon", "still-theme-carnival.png", 0.545, 0.565, 3.2, "One balloon per worry.", "The longer it waits, the tighter it swells.", "dusk", "One Current Pro"],
    ["z2-zoom-cat", "still-theme-catnap.png", 0.545, 0.585, 3.2, "It waits. Politely.", "Answer the cat, and it curls up.", "warm", "One Current Pro"],
    ["z3-zoom-angler", "still-theme-abyss.png", 0.545, 0.585, 3.2, "Light in the deep.", "The louder it grows, the brighter its lure.", "night", "One Current Pro"],
    ["z4-zoom-pup", "still-theme-pompom.png", 0.545, 0.585, 3.2, "Small. Loud. Loyal.", "Leave it waiting, and it barks.", "warm", "One Current Pro"],
    ["z5-zoom-ghost", "still-theme-gravemist.png", 0.545, 0.585, 3.2, "A gentle haunting.", "Its wail widens until you answer.", "dusk", "One Current Pro"],
    ["z6-zoom-now", "still-hero.png", 0.61, 0.5, 3.0, "Now has a pulse.", "Your present moment, always moving.", "river", "One Current"],
    ["z7-zoom-curve", "still-hero.png", 0.4, 0.53, 2.6, "The line that comes back.", "Integrated threads curve home into Now.", "river", "One Current"],
    ["z8-zoom-check", "still-hero.png", 0.535, 0.428, 3.4, "The quiet ✓ of “decided today.”", "Not solved. Answered. That counts.", "warm", "One Current"],
    ["z9-zoom-steps", "still-hero.png", 0.8, 0.52, 2.4, "Small steps live on your line.", "Decided actions sit right on today.", "river", "One Current"],
    ["z10-zoom-loud", "still-loud.png", 0.35, 0.31, 2.8, "This is what “loud” looks like.", "Thicker, wilder, further from your line.", "night", "One Current"],
  ].map(([key, still, x, y, zoom, headline, sub, mood, kicker]) => ({
    key: key as string,
    formats: ["45", "story"] as (keyof typeof F)[],
    mood: mood as Concept["mood"],
    layout: "zoom" as const,
    still: still as string,
    focus: { x: x as number, y: y as number, zoom: zoom as number },
    kicker: kicker as string,
    headline: headline as string,
    sub: sub as string,
  })),
];

export const posters: PosterDef[] = concepts.flatMap((c) =>
  c.formats.map((f) => {
    const { key, formats, ...rest } = c;
    return { id: `${key}-${f}`, ...F[f], ...rest };
  }),
);
