/* Fold every public/footage/<scene>.beats.json into src/beats.generated.json,
   so compositions can anchor cues to beat labels instead of raw frame numbers.
   The footage itself is gitignored; this small map is committed, which keeps
   renders reproducible and lets the scripts be reviewed without 130MB of webm.
   Run after any capture:  node promo/scripts/sync-beats.mjs */
import { readdir, readFile, writeFile } from "node:fs/promises";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const promoDir = dirname(dirname(fileURLToPath(import.meta.url)));
const footage = join(promoDir, "public", "footage");
const out = join(promoDir, "src", "beats.generated.js");

const files = (await readdir(footage)).filter((f) => f.endsWith(".beats.json")).sort();
const map = {};
for (const f of files) {
  const raw = JSON.parse(await readFile(join(footage, f), "utf8"));
  const name = f.replace(/\.beats\.json$/, "");
  map[name] = {
    frames: raw.frames,
    fps: raw.fps ?? 30,
    beats: Object.fromEntries((raw.beats ?? []).map((b) => [b.label, b.frame])),
  };
}
await writeFile(
  out,
  "/* Generated by scripts/sync-beats.mjs — do not edit. */\n" +
    "export const beats = " + JSON.stringify(map, null, 2) + ";\n",
);
console.log(`beats: ${files.length} scenes → src/beats.generated.js`);
for (const [k, v] of Object.entries(map)) {
  console.log(`  ${k.padEnd(20)} ${String(v.frames).padStart(5)}f  ${Object.keys(v.beats).join(" ") || "(none)"}`);
}
